parameters:
  # Adds a fallback DATABASE_URL if the env var is not set. This allows you to run cache:warmup even if your environment variables are not
  # available yet. You should not need to change this value.
  env(TEST_DATABASE_URL): ''

doctrine:
  dbal:
    driver: "pdo_pgsql"
    server_version: "13.2"
    charset: utf8
    url: '%env(resolve:DATABASE_URL)%'
    schema_filter: '~^(?!(?:domain_messages)|(?:domain_snapshots)|(?:messenger_messages)|(?:lock_keys)|(?:event_handler_progress))~'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    report_fields_where_declared: true
    enable_lazy_ghost_objects: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
      DomainState:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Domain'
        prefix: 'App\Domain'
        alias: DomainState

when@test:
  doctrine:
    dbal:
      url: '%env(resolve:TEST_DATABASE_URL)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
