framework:
    router:
        utf8: true

when@prod:
    framework:
        router:
            strict_requirements: null
when@dev:
  framework:
    router:
      strict_requirements: true

when@test:
  framework:
    router:
      strict_requirements: true
