version: '3.7'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./mobile/.well-known:/var/www/html/mobile/.well-known:rw,cached
      - ./public/:/var/www/html/public:rw,cached
      - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/nginx/newdigitals-challenge.dev.pem:/etc/nginx/certs/newdigitals-challenge.dev.pem:ro
      - ./.docker/nginx/newdigitals-challenge.dev-key.pem:/etc/nginx/certs/newdigitals-challenge.dev-key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  api:
    build:
      context: ./.docker/api
    volumes:
      - code:/var/www/html
      # Exclude node modules
      - /var/www/html/node_modules
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  database: ~
  code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
