services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Service Definition to avoid Missing Service warnings
  App\Time\TestClock: ~
  App\Test\Service\Emails\EmailsFake: ~

  # Interface autowiring
  App\Time\Clock: '@App\Time\TestClock'
  App\Service\Emails\Emails: '@App\Test\Service\Emails\EmailsFake'

  App\Test\Service\:
    resource: '../tests/Test/Service/*'

  App\Test\EntityHelper\:
    resource: '../tests/Test/EntityHelper/*'
    public: true
